config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home', as: :home
  get '/about', to: 'pages#about', as: :about
  get '/contact', to: 'pages#contact', as: :contact

  resources :cocktails, only: [:index, :show, :new, :create] do
    resources :doses, only: [:new, :create]
  end
  resources :doses, only: [:delete]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses

  validates :name, uniqueness: true, presence: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :description, presence: true
  validates :cocktail, uniqueness: { scope: :ingredient }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses

  validates :name, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def home; end

  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
    @new_dose = Dose.new
  end

  def new
    @new_cocktail = Cocktail.new
  end

  def create
    create_cocktail = Cocktail.create(cocktail_params)

    redirect_to cocktail_path(create_cocktail)
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new; end

  def create
    create_dose = Dose.new(dose_params)
    cocktail = Cocktail.find(params[:cocktail_id])
    create_dose.cocktail = cocktail
    create_dose.save
    redirect_to cocktail_path(cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home; end

  def about; end

  def contact; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/cocktails/index.html.erb
<div class="index-background">
  <div class="navbar">
    <div class="languages">
      <p><%= link_to 'EN', 'pages#home' %> / </p>
      <p><%= link_to 'ES', 'pages_es#home_es' %> / </p>
      <p><%= link_to 'CAT', 'pages_cat#home_cat' %> </p>
    </div>
    <div class="tabs">
      <%= link_to 'Home', home_path %>
      <%= link_to 'Cocktails', cocktails_path %>
      <%= link_to 'About', about_path %>
      <%= link_to 'Contact', contact_path %>
    </div>
    <%= link_to 'https://www.lewagon.com/', target: :_blank do %>
      <%= image_tag 'lewagon-logo-black.png' %>
    <% end %>
  </div>

  <a class="to-top" href="#top">
    <div class="container title">
      <h1>All your cocktails</h1>
    </div>
  </a>

  <div class="flex-container container">
      <% @cocktails.each do |cocktail| %>
        <%= link_to cocktail.name do %>
          <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= "https://source.unsplash.com/featured/?#{cocktail.name.delete(' ').delete("'")},cocktail" %>)">
            <p> <%= cocktail.name %> </p>
          </div>
          <% end %>
      <% end %>
  </div>
</div>

app/views/cocktails/new.html.erb
<div class="navbar">
  <p> <%= link_to '< Go back', cocktails_path %> </p>
</div>
<div class="container">
  <%= simple_form_for(@new_cocktail) do |f| %>
    <%= f.input :name %>
    <%= f.submit %>
  <% end %>
</div>

app/views/cocktails/show.html.erb
  <div class="cocktail-banner">
    <img src= <%= "https://source.unsplash.com/1600x900/?#{@cocktail.name},cocktail" %>>
    <p> <%= @cocktail.name %> </p>
  </div>
<div class="show-container">
  <div class="show-navbar">
    <p> <%= link_to '< Go back', cocktails_path %> </p>
  </div>
  <h2> <%= @cocktail.name %> </h2>
  <p> <%= link_to 'Create new dose', new_cocktail_dose_path(@cocktail) %> </p>

  <div class="grid-cocktail-container">
    <div class="cocktail-info">
      <% @cocktail.doses.each do |dose| %>
        <% ingredient = Ingredient.find(dose.ingredient_id) %>
        <p> <%= "#{dose.description} #{ingredient.name}" %> </p>
      <% end %>
    </div>

    <div class="dose-form">
      <%= simple_form_for([@cocktail, @new_dose]) do |f| %>
        <%= f.input :description %>
        <%= f.association :ingredient %>
        <div class="submit-btn"> <%= f.submit %> </div>
      <% end %>
    </div>
  </div>
</div>

app/views/doses/new.html.erb
<div class="container">
  <%= simple_form_for([@cocktail, @new_dose]) do |f| %>
    <%= f.input :description %>
    <%= f.association :ingredient %>
    <%= f.submit %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
about.html.erb

app/views/pages/contact.html.erb
contact.html.erb

app/views/pages/home.html.erb
<div class="navbar">
  <div class="languages">
    <p><%= link_to 'EN', 'pages#home' %> / </p>
    <p><%= link_to 'ES', 'pages_es#home_es' %> / </p>
    <p><%= link_to 'CAT', 'pages_cat#home_cat' %> </p>
  </div>
  <div class="tabs">
    <%= link_to 'Home', home_path %>
    <%= link_to 'Cocktails', cocktails_path %>
    <%= link_to 'About', about_path %>
    <%= link_to 'Contact', contact_path %>
  </div>
  <%= link_to 'https://www.lewagon.com/', target: :_blank do %>
    <%= image_tag 'lewagon-logo-black.png' %>
  <% end %>
</div>

<div class="home-banner">
  <div class="text-container container">
    <h1>Cocktail your live</h1>
    <p>Your cocktail library</p>
    <%= link_to 'Add new cocktail', new_cocktail_path %>
  </div>
</div>

<div class="container">
  <div class="content">
    <div class="grid-body-container">
      <p>Lorem ipsum dolor sit amet consectetur, adipisicing, elit. Dicta accusantium cum, laboriosam autem ut facere temporibus expedita et quas, ipsa molestias nihil error consequuntur facilis quae quaerat quidem fuga sequi. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Commodi, ullam delectus cumque repudiandae quidem. Fuga libero sit maxime tempore magni saepe labore qui facilis, debitis quibusdam repudiandae ea, vero quasi.</p>
      <img src="https://okdiario.com/img/2018/07/02/receta-de-cocktail-de-martini-con-limon-1.jpg" alt="">
    </div>
    <div class="grid-body-container-reverse">
      <img src="https://i0.wp.com/www.cakesandpumps.com/wp-content/uploads/2016/12/Cosmopolitan-cocktail-cocktail-friday-1.jpg?fit=1000%2C665&ssl=1" alt="">
      <p>Lorem ipsum dolor sit amet consectetur, adipisicing, elit. Dicta accusantium cum, laboriosam autem ut facere temporibus expedita et quas, ipsa molestias nihil error consequuntur facilis quae quaerat quidem fuga sequi. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Commodi, ullam delectus cumque repudiandae quidem. Fuga libero sit maxime tempore magni saepe labore qui facilis, debitis quibusdam repudiandae ea, vero quasi.</p>
    </div>
    <div class="grid-body-container">
      <p>Lorem ipsum dolor sit amet consectetur, adipisicing, elit. Dicta accusantium cum, laboriosam autem ut facere temporibus expedita et quas, ipsa molestias nihil error consequuntur facilis quae quaerat quidem fuga sequi. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Commodi, ullam delectus cumque repudiandae quidem. Fuga libero sit maxime tempore magni saepe labore qui facilis, debitis quibusdam repudiandae ea, vero quasi.</p>
      <img src="https://i1.wp.com/www.eatthis.com/wp-content/uploads/2019/03/old-fashioned-cocktail.jpg?w=640&ssl=1" alt="">
    </div>
  </div>
</div>